### ISSUE TITLE
RP2040 with sport and castle not working

### ISSUE THREAD

**Issue by jdowdle** [dgatf/msrc#101]
Hello Daniel,
I have built and programmed a RP2040 zero board per your instructions from gethub master.
The esc motor command gets thru, but there is no telemetry nor blinking led.
Tried redoing programming and config multiple times.
This setup has run with an Arduino board, though all tlm except current works.
I am confused by some posts I see here earlier. You commented that 5v tolerance is a problem with castle, maybe a voltage divider is needed.
Do I need a voltage divider ? I wonder how this would work at all with esc motor commands coming through if this is the problem.
I am currently using the 1k pullup to Castle. From the receiver side, I have a Frsky receiver.
The RP board I have came from Amazon, it says it has a ME621 LDO. Could my problem be I am feeding power to the board from the sport?? as you mentioned here earlier? Would that prevent TLM from working, but allow throttle commands to pass thru??
Also, I am concerned about connecting higher voltage to my 5v input. I found a ME6211 (I believe), it said 6.5v max. I am currently getting 8v from castle, could set to 6v.
Any suggestions? thx.
PS: I am confused from earlier discussion, does the 3-color LED work?

**Comment by dgatf** [comment]
Fixed with 33585ca3531d00a9905ecfa0e9957d370f44e846
