### ISSUE TITLE
Jeti - How to give the sensor a name

### ISSUE THREAD

**Issue by andypnz** [dgatf/msrc#104]
Hi. Any idea how to give the overall sensor a name to appear on the Jeti telemetry setup screen? 

Like this says 'RCT Amp'

![image](https://user-images.githubusercontent.com/11356342/219850894-3ae3dc3e-6414-4517-8ce6-451f50dc9141.png)

I think it is the "zero-valued identifier is used to give a name to the device itself"

![image](https://user-images.githubusercontent.com/11356342/219908732-1493ef46-6ff1-4cb0-997c-2306657a1523.png)

**Comment by dgatf** [comment]
Added a sensor name with commit 90b33f1b474ae7fe1d8ff1324bb75e0aa57c5ffd
