### ISSUE TITLE
About RP2040 Indicators are not blinking

### ISSUE THREAD

**Issue by aepub** [dgatf/msrc#106]
I used RP2040. After copying mlsrc-RP2040. uf2 into the RP2040 folder, the indicator lights did not blink. It was found that the RGB (WS2812B) indicator lights were used on the original board, and it seems to be LED in your code. Because I found that there are led.c and led.h, how should I modify to have the indicator light?

**Comment by dgatf** [comment]
Fixed with https://github.com/dgatf/msrc/commit/1a3f299f7e3c4cdfac2c9b15cf074ee6aff59de2
