### ISSUE TITLE
Some detailed info for readme...

### ISSUE THREAD

**Issue by DarthRye** [dgatf/msrc#109]
S!

Dont know where to find that info, so sorry if this is not the place.

I would know the list of materials needed and its detailed specs ( resistor wattage for example)

Also would be nice to find some pictures of  where to connect telemetry on  ESC, for  example Hobbywing Flyfun v5 ESC, where readme says its not the programa cable nor the throttle one.

Thx for the effort.

**Comment by dgatf** [comment]
Based on the manual you have to connect the program wire (3) to GPIO5 and select Hobbywing V4 protocol to have full telemetry
