### ISSUE TITLE
msrc.lua does not work on TX16S

### ISSUE THREAD

**Issue by twistedwings** [dgatf/msrc#11]
Screen is flickering, script not useable.

Radiomaster TX16S
OpenTX 2.3.10

**Comment by dgatf** [comment]
Please try with the updated lua script

If flickering persists please detail when is occuring (always, when pressing enter to select...) and where (all display, selected element...)

**Comment by twistedwings** [comment]
no change with updated script.
I've made a video, it's hard to describe in words.

https://drive.google.com/file/d/1QKCs-_PDaVhlGduLLaQ6e0dzwH0fgkBd/view?usp=sharing

**Comment by dgatf** [comment]
Hopefully now is fixed. Please try again with the updated script

**Comment by twistedwings** [comment]
now it seems to work, thank you...
