### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by jasc76** [dgatf/msrc#110]
Hi

is there any debug possiblity to see if the sensors are seen correct by the rp2040?

**Comment by jasc76** [comment]
This is not what I meant. I thought smth like oXs where I can check the outputs via console (serial terminal)

**Comment by jasc76** [comment]
How does it work?

 

Von: Guo ***@***.***> 
Gesendet: Dienstag, 2. Mai 2023 17:07
An: dgatf/msrc ***@***.***>
Cc: jasc76 ***@***.***>; Author ***@***.***>
Betreff: Re: [dgatf/msrc] debugging (Issue #110)

 

MSRC has a debug mode, but the information available is still limited!

**Comment by dgatf** [comment]
You can enable debug mode from MSRC_GUI:

![Captura desde 2023-07-18 19-38-40](https://github.com/dgatf/msrc/assets/33811722/ef092c3c-88fd-47dd-9ea4-a362f2c18176)

Then close MSRC_GUI and use any serial monitor (you can use arduino's) at 115200
