### ISSUE TITLE
XBUS Transistor

### ISSUE THREAD

**Issue by jasc76** [dgatf/msrc#112]
Hi
can someone please show a picture of the transistor circuit needed for XBUS?
THanks !!

**Comment by dgatf** [comment]
You can see in MSRC_GUI when selecting XBUS protocol and clock stretch

![Captura desde 2023-07-19 12-15-36](https://github.com/dgatf/msrc/assets/33811722/e0f2a54e-4c33-469e-8ee6-4cd37891b859)

**Comment by jasc76** [comment]
thanks
sorry, but is the connection of the third resistor really correct? like this you connect the pin with the green wire directly to 3.3V ?
