### ISSUE TITLE
Improper Pathing in .vscode

### ISSUE THREAD

**Issue by codydg** [dgatf/msrc#114]
`.vscode` contains two version-tracked files: `launch.json` and `settings.json`

Both files use `/home/daniel/...` several times, making it very specific to the author's directory structure

In `launch.json`, the `gdbPath` and `searchDir` include it.

In `settings.json`, the `cortex-debug.openocdPath` and `cortex-debug.armToolchainPath`

**Comment by dgatf** [comment]
Fixed with 2c1e3b72fb13a9f1f2e2f7ce778f072f32f492f8
