### ISSUE TITLE
FlySky no longer functions with new binary

### ISSUE THREAD

**Issue by saito180** [dgatf/msrc#133]
The new binary now works for futaba, I now get Temp readings to my transmitter from the T-FHSS receiver,
unfortunately ALL communication to FlySky IBUS is gone with the new binary, no led or anything.

**Comment by dgatf** [comment]
Fixed with [commit](d542785)

[Binary](https://drive.google.com/file/d/1pzIt4XdcLxiSUfSTfyoh_w5tLTFd9JN2/view?usp=drive_link) updated.
