### ISSUE TITLE
Vario wroks not korekt with Jeti 

### ISSUE THREAD

**Issue by Klippeneck** [dgatf/msrc#138]
I have tested the changes, unfortunately without success.
The sensor name does not appear in the telemetry display.
Only 2 values appear for the vario, air temperature and abs. altitude, vario value is missing.
The vario value only appears when the additional GPS is configured, but is somewhat unstable.
See screenshots of the display.

![Screen005 3829](https://github.com/user-attachments/assets/cbff6d42-53e9-43f2-8eda-ac126055847e)
![Screen004 3828](https://github.com/user-attachments/assets/ebc4e945-35c5-49e7-9642-113b55338917)
Jürgen

**Comment by Klippeneck** [comment]
Sensor value jumps between +-0.5m/s.
Yes, the v Speed value now has 2 digits after the decimal point.
But the v Speed value only appears when the GPS is activated, with vario only there is no v Speed value. 
Jürgen

**Comment by dgatf** [comment]
There was some issues with the buffer creation due to the changes. Hopefully it is fixed now with commit 30073882f457e076e86d986697b8759b7fdda04b

Please flash updated [binary](https://drive.google.com/file/d/1pzIt4XdcLxiSUfSTfyoh_w5tLTFd9JN2/view?usp=drive_link).

**Comment by Klippeneck** [comment]
The change has not been successful, on the contrary.
Now there are no values at all for the vario and also for GPS.
In addition, the sensor does not always start at Power On and can only be brought back to life by pressing the reset button on the RP 2040 several times. Only then does the LED light up.
Jürgen

**Comment by dgatf** [comment]
I've reverted some of the changes. Changes now are only: no mute and maximum sensors 15

If this works (it should), I'll leave as is an forget about the sensor name.

Flash updated [binary](https://drive.google.com/file/d/1pzIt4XdcLxiSUfSTfyoh_w5tLTFd9JN2/view?usp=sharing)

**Comment by Klippeneck** [comment]
With this version, the vario works with all 3 values.
Temperature and altitude seem plausible, the vario value jumps between plus minus 0.56 m/s with steps of 0.18 m/s, i.e. 0.18, 0.37 and 0.57 m/s positive and negative respectively.
There are no intermediate values.
Jürgen

**Comment by dgatf** [comment]
Ok. Good. So the only change removed is the sensor name.

I'll check the vario resolution. To smooth vario values you can increase the number of averaging elements for vario.

![imagen](https://github.com/user-attachments/assets/ad88e403-b251-4a46-897a-eec6d63ab76a)

**Comment by dgatf** [comment]
Vspeed works better when moving. But also if the interval used to calculate vspeed is low, it makes vspeed more sensitive to noise. For now this parameter is hardcoded but I could populate yo msrc_gui.

See the [interval](https://github.com/dgatf/msrc/blob/ce9af81b8b2b147f742d75e4fe3e0a495ce78b87/board/project/sensor/bmp280.c#L58)

The interval is 500ms, but it could be increased to 1 or 2 seconds to smooth vspeed
