### ISSUE TITLE
Lua script doesn't work on Horus

### ISSUE THREAD

**Issue by TomasJot** [dgatf/msrc#2]
Fails on line 307 "lcd.drawText(410, 220, config.i2c1Address, getFlags(17))" with error "bad argument #3 to 'drawText' (string expected)" (and other couple of lines)...

**Comment by dgatf** [comment]
Thanks. Horus display is fixed https://github.com/dgatf/msrc/commit/05c3a8e8f08a4cc3eb9dc5ee43ed5e4130c28792
