### ISSUE TITLE
Voltage/Current sensor

### ISSUE THREAD

**Issue by stefaanbolle** [dgatf/msrc#27]
I have following V/C-sensor [http://www.rctimer.com/rctimer-voltage-amp-current-sensor-90a-w-xt60-kit-p0476.html](url)
It has a INA169 that provides the measured output. Can I just connect the V to the Voltage1 pin, the A to the Current pin and GND to GND on the Mega2560?
Does it work out of the box with the V and C measuring code?

**Comment by dgatf** [comment]
Yes. Then you have to adjust in opentx the sensors with a ratio 1000/sensitivity

**Comment by stefaanbolle** [comment]
Thanks

**Comment by stefaanbolle** [comment]
Voltage is reported as A3. Value looks good
