### ISSUE TITLE
rpm limited ?

### ISSUE THREAD

**Issue by twistedwings** [dgatf/msrc#28]
I am using an Arduino Pro Mini 3.3V/8Mhz with voltage1 and rpm sensors configured.
Rpm signal goes from a HW phase sensor to pin 8.
Rpm telemertry works up to about 2000 rpm, above 2000 rpm it drops to zero.
The signal on pin 8 is still there (about 1700 Hz).

I am running the same configuration with an 5V/16Mhz Arduino Pro Mini without problems.
Is the  3.3V/8Mhz too slow (I cannot believe that) ?

**Comment by dgatf** [comment]
Not too slow. It is because I used a 16Mhz board and it was needed to reduce the timer to avoid an 'overflow' for 8Mhz. Well, at least in theory... I don't have a 8Mhz now

Please try the updated code

**Comment by twistedwings** [comment]
still the same problem...

**Comment by dgatf** [comment]
Changed timer scaler (maybe timer scaler was too slow for 8Mhz). It will also produce better accuracy at higher rpms

Please try updated code

**Comment by twistedwings** [comment]
seems to be fixed, thank you...
