### ISSUE TITLE
Example code for xbus

### ISSUE THREAD

**Issue by jeanbatfr** [dgatf/msrc#35]
Hi, I need to convert an analog signal from a temperature sensor to the xbus port of my spektrum receiver. I will use a little Trinket 3v as arduino board.
Do you have an example code in order to understand how to use functions from xbus.h?
I'm a liitle bit lost at the moment ^^

Thank you

**Comment by dgatf** [comment]
xbus.h is not intended to work as an arduino library. But basically in _begin_ you set the mask for i2c, its request are handled with _i2c_request_handler_ and in _update_ you get new values of the sensors and copy the the strucs that are sent in the handler. See xbus [specs](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjwjcXHgsbvAhXMPsAKHQuPDfsQFjABegQIAhAD&url=https%3A%2F%2Fspektrumrc.com%2FProdInfo%2FFiles%2FSPM_Telemetry_Developers_Specs.pdf&usg=AOvVaw1JhzO5etKGown2ZBfaOdKi)

I recommend to use a supported board and use _msrc_ as is
