### ISSUE TITLE
Lua Script

### ISSUE THREAD

**Issue by Frodcem** [dgatf/msrc#39]
HI,
My radio is Radiomaster, receiver X8R Fr sky.
Board Arduino Pro Mini Atmega 328P
I have problem. I run lua script and all time is connecting on screen.
What I do wrong?

Robert

**Comment by jogybaer0815** [comment]
Check if you have selected the matching processor in Arduino (Pro Mini) and wire Smartport pin to D7 and D12 with 2k2-3k3 resistor. If connection to receiver exists, the onboard LED (pro Mini) flickers and lua script is able to connect.
No need to have telemetry-input for smartport-connection check
