### ISSUE TITLE
lua script dont work on T16

### ISSUE THREAD

**Issue by loetefix** [dgatf/msrc#4]
Hi,

On OpenTx 2.3.7 the lua script bring the Jumper T16 to freeze.

**Comment by loetefix** [comment]
Hi,
It freeze on init. When i execute the script the display freeze directly. Not even the LCD clears or show something from the script. It dont matter if the model is connected or the Arduino. The steering of the model is possible while that. But i cant exit the script. I have to disconnect the battery from the transmitter. In the companian it works in the simulater. I can try it on horus if i have some time.

**Comment by dgatf** [comment]
Working on other T16
