### ISSUE TITLE
strange sensors 5100, 5101, 5102

### ISSUE THREAD

**Issue by twistedwings** [dgatf/msrc#44]
what do these sensors mean, or is it a bug ?

![image](https://user-images.githubusercontent.com/562809/130898893-14bb8cd7-10d0-488b-931c-62fef1eb906f.png)

Radiomaster TX16S
OpenTX 2.3.14
msrc 0.8

**Comment by dgatf** [comment]
It's not a bug. Those sensors contains the signature and raw current for HW4 ESCs. Comment line 26 in config.h `#define ESC_SIGNATURE` to remove them

**Comment by twistedwings** [comment]
I see.
It would be nice to see them in the docu.
