### ISSUE TITLE
HW V4 EscC always 0

### ISSUE THREAD

**Issue by twistedwings** [dgatf/msrc#46]
EscC is always 0.

![image](https://user-images.githubusercontent.com/562809/132135916-f2160d98-21ea-4a23-aefd-376bcfc43735.png)

Hobbywing Platinum V4 80A
Arduino Mini 3.3V/8MHz
RadioMaster TX16S
OpenTX 2.3.14

**Comment by dgatf** [comment]
It's been always like that. I haven't implemented the consumption calculation yet. For that you can add a sensor:

- type _calculated_
- formula _consumpt_
- sensor _EscA_
