### ISSUE TITLE
No data via XBUS on AR8020T

### ISSUE THREAD

**Issue by LuHaGH** [dgatf/msrc#53]
The final goal is to use a HW V4 120A LV with the AR8020T, everything with the latest firmware.

I use an ATmega328P Arduino Pro Mini 3.3V.

`#define RX_PROTOCOL RX_XBUS`
`/* Sensors */`
`#define CONFIG_ESC_PROTOCOL PROTOCOL_HW_V4_LV`

I tried with

`/* Use library I2C_T3 for Teensy LC/3.X */`
`//#define I2C_T3_TEENSY`

or without, but nothing works.

So I tried without the ESC connected and 

`#define SIM_SENSORS`

but I still receive no ESC data at my transmitter. The AR8020T internal altitude, BEC voltage and Flight Log are working.

**Comment by LuHaGH** [comment]
> Just to confirm. With enabled DEBUG and disabled SIM_RX, do you see any 20 0 2 DE 9 20 0 E0 0 0 0 E7 0 0 0 0 ?

No, if I not enable SIM_RX I don't see anything in the log. And you are right, I only get the "V800" when I switch the Baud Rate.

I've flashed your testing sketch but I don't have any log entries after that, too.

Maybe the integrated barometer to provide altitude and vario telemetry of the AR8020T is the problem. The receivers Oki188 tested, are without internal sensors.

**Comment by dgatf** [comment]
Which sensors have you enabled in the telemetry screen on the transmitter?

**Comment by dgatf** [comment]
Disconnect 3.3v líne from the receiver and feed the Arduino with 5v from any servo connector

**Comment by LuHaGH** [comment]
> For some reason the receiver is not sending any telemetry request or the arduino is not receiving those requests. Try adding pull up resistors (2k to 10k) to sda and scl lines (one for each line). Sometimes built in pull ups are not enough.

I will try this on Sunday.

> Which sensors have you enabled in the telemetry screen on the transmitter?

Up to now altitude, BEC Voltage and Flight Log. I've tried the autodetection, it found nothing new, so I enabled ESC, flight battery voltage and current manually.

> Disconnect 3.3v líne from the receiver and feed the Arduino with 5v from any servo connector

There is no regulated 3.3V line at the XBus port. Only the sda and scl lines are pulled to 3.3V. The VCC line is at the same voltage as the servos, in my case 6.0V.

**Comment by LuHaGH** [comment]
I have a little success. If I power up the Arduino first with a dedicated LiPo and a few seconds later the AR8020T then the communication is starting.
But in "production use" I have no possibility to start the Arduino first and the AR8020T later.

Is there a possibility to speed up the booting of the Arduino?

**Comment by LuHaGH** [comment]
I used an old Arduino UNO as ISP (of course with loaded ArduinoISP) and flashed the Arduino Pro Mini without bootloader. So it is booting up fast enough to answer the sensor request form the AR8020T.

Is it normal, that I get the voltage from the main battery only after the first start of the motor and the RPM is not getting back to "0" after stopping it?

**Comment by dgatf** [comment]
You're right. Arduino was too slow answering the initial poll.

I've done a two thinks to improve this:

- Move i2c sensors to higher addresses (>0x70) as we're free to choose that. That's about 22ms*100 = 2.2 seconds. This alone should be enough
- Add a i2c clock stretch as the first instruction so it stops i2c until arduino is ready (hoping this happens before the first poll, but depends on the bootloader delay)

**Comment by dgatf** [comment]
> Is it normal, that I get the voltage from the main battery only after the first start of the motor and the RPM is not getting back to "0" after stopping it?

No, voltage and rpm should be correct all the time. This may be related to the esc firmware, tht is not updating those values all the time. Please post the DEBUG and DEBUG_HW4 together to verify

**Comment by LuHaGH** [comment]
Both ideas are not working.
First I restored the bootloader and flashed with TTL programmer. No ESC sensors found and no delay in the receiver.
Second I used the ISP again. With that installation the whole receiver is blocked about 5 seconds, even the ESC is giving a warning for "no signal" and I got no telemetry data too.

Maybe there is a reason for the forbidden clock stretching in the XBus documentation ;-)

I will restore the previous xbus.h and xbus.cpp and try to debug the HW4 tomorrow.

**Comment by dgatf** [comment]
I've removed the clock stretching... not sure if that was an issue

But I keep the higher i2c addresses . That has to work. Could you please test it. You may need to run autdetection again

**Comment by KHeintz** [comment]
Do not use a bootloader together with XBUS.

**Comment by KHeintz** [comment]
A pitfall with Teensy can be in Arduion hardware/ teensy/avr/cores/ teensy3 / pins_teenys.c the anlog init nee following change. AR8010T may otherwise have problems with the XBUS.

analog_init();
	delay(5);
	usb_init();
	delay(5);

**Comment by LuHaGH** [comment]
> I keep the higher i2c addresses. That has to work. Could you please test it. You may need to run autdetection again

Neither with autodetection nor with manual enabling ESC I got telemetry in my transmitter with the higher i2c addresses.

Why do you left the "delay(5000)" in the xbus.cpp line 102. I think you have removed the clock stretching?

> This may be related to the esc firmware, which is not updating those values all the time. Please post the DEBUG and DEBUG_HW4 together to verify

You are right, only when the motor is is running the ESC is transferring data.
[ESC-XBus.txt](https://github.com/dgatf/msrc/files/7449668/ESC-XBus.txt)

I think we can close this issue, cause the solution is to program the arduino without bootloader.

**Comment by dgatf** [comment]
Damn, the delay is the mistake. Could you comment It and flash again. It really has to work with any I2C address

**Comment by LuHaGH** [comment]
Sorry, it's not working with commented "delay(5000)". You will have to revert to the previous state.

**Comment by dgatf** [comment]
Reverted to previous I2C addresses. Fixed
