### ISSUE TITLE
BMP280 and Ibus

### ISSUE THREAD

**Issue by erwann56** [dgatf/msrc#61]
I quickly tested the "BMP280 module 3.3V (6 pins, I2C/SPI)" with GPS and voltage.
I have 3 additional sensors which appear TEMP1, 00Gp and Vspd).
Temp1 displays 40° and the others are at 0.
GPS and voltage are OK.
I connected the BMP280 to the arduino nano at 3.3v, GND, A4 and A5. Did I forget something?

**Comment by dgatf** [comment]
Fixed now. Flash updated code

**Comment by erwann56** [comment]
I always have the BMP values ​​at 0 except TEMP1 at -40.
I did a scan of the i2c port, I can't find my sensor.
I do not understand why. I'll keep you informed.

**Comment by erwann56** [comment]
The i2c scan finds it with the address 076. (dry solder on A4)
The telemetry is always identical temp1 -40 and alt at 0.

**Comment by dgatf** [comment]
- Check connections
- Check SDA/SCL are not swapped
- You are using arduino at 5V, so you should use the 5V version (4 pins) of the BMP280. See [remark](https://github.com/dgatf/msrc#34-i2c-sensors). If it is the 3.3v version (6 pins), you may have burnt it (it may not get burn if sensor Vcc is connected to 3.3v, but still could be due to I2C at 5v)

**Comment by erwann56** [comment]
![Uploading sensor test.png…]()

**Comment by erwann56** [comment]
I will test again but everything seems OK at the sensor level.
For the I2C address, should I leave 119 or put 76?


![sensor test](https://user-images.githubusercontent.com/44725865/153642584-9367363e-db3a-4b96-8bfe-9402180f4ce2.png)

**Comment by erwann56** [comment]
![1644603190465](https://user-images.githubusercontent.com/44725865/153647083-ddd17cf0-afbd-4bd7-8928-aa3b309df28c.jpg)

It was an address problem. I had to put 118.
However, there is a lag for temperature.
Instead of 21°c I have -18°c.

**Comment by erwann56** [comment]
Everything is perfect.
