### ISSUE TITLE
Smartport, GPS, voltage and BMP280

### ISSUE THREAD

**Issue by erwann56** [dgatf/msrc#62]
I just tested this configuration. There are several remarks:
- Gspd to KTS
- Vspd inconsistent value
- Absence of BMP280 vario
- Absence of ALT BMP280

- GPS coordinates ok
- Voltage ok
- Galt ok
- hdg ok
![1644686957973](https://user-images.githubusercontent.com/44725865/153721976-e1c61a94-fe34-4584-a942-659f35f92fdf.jpg)

**Comment by dgatf** [comment]
> Gspd to KTS

KTS is the default unit for GPS speed in smartport. Value should be in accordance with KTS

> Absence of BMP280 vario
> Absence of ALT BMP280

Does this happen when only is enabled BMP280 (and GPS disabled)?

**Comment by erwann56** [comment]
Exactly the same thing. The GPS is not disabled despite a "false" in the config.h
Indeed, there is no temperature.

**Comment by dgatf** [comment]
You need to disable CONFIG_LUA in config.h

**Comment by dgatf** [comment]
> Vspd inconsistent value

Fixed with b2adecfe25f86e3658dc3b555ad21b419e5ce6c3

**Comment by erwann56** [comment]
GPS, Voltage and BMP280 sensors are ok, when CONFIG_LUA in config.h is disabled

**Comment by dgatf** [comment]
Would be interesting to compare GPS vario with BMP280 vario. BMP280 is expected to provide much more accurate values

**Comment by erwann56** [comment]
I actually think the pressure will be more accurate than the GPS. I will test during my next outing in the mountains and I will give you the result
