### ISSUE TITLE
FSIA6B and LAT / LON

### ISSUE THREAD

**Issue by erwann56** [dgatf/msrc#65]
It's not really important but with the IA6B receiver, the GPS LAT and LON telemetry is at 0.
With the FSiA10B everything is ok.

![1644829786052](https://user-images.githubusercontent.com/44725865/153837254-f79b0ca7-8371-4311-8d41-5b3f1540ec67.jpg)

**Comment by dgatf** [comment]
It seems that not all IA6B supports [4 bytes ](https://github.com/betaflight/betaflight/issues/6319)telemetry. Though you can update the [firmware](https://github.com/povlhp/FlySkyRxFirmware) to last stock version which probably does
