### ISSUE TITLE
Sbus can not work with GPS on arduino pro mini？

### ISSUE THREAD

**Issue by nfsboy** [dgatf/msrc#80]
Sbus can not work with GPS on arduino pro mini？ I try connect futaba 7008  and futaba 3008，it dose not working

**Comment by dgatf** [comment]
Please provide more information:
- Board used
- Post config.h
- Does it work without GPS?

**Comment by nfsboy** [comment]
Thank you ，I fix it，because my pro mini use 5v  and 16M，but I try burn it ues 3.3v 8M。
 Now , I try same config working on the arduino nano 5V and 16M , works very well。
