### ISSUE TITLE
S-PORT/Teensy 3.2 return me no telemetry

### ISSUE THREAD

**Issue by pierrotm777** [dgatf/msrc#85]
Hello Daniel,

I try to build my own telemetry with an Teensy 3.2 board.
My S-Port use the pin 1 (TX1).

I try the Debug feature without success:
#define DEBUG
#define DEBUG_GPS
#define SIM_SENSORS

My GPS is connected to the pins:
GPS Rx on pin 8
Gps Tx on pin 7

Can you help me please ?
Pierre

**Comment by dgatf** [comment]
Based on you r debiug, the GPS is ok and Teensy is sending the telemetry to the receiver. It should be ok. I've tested this with Teensy LC and it's ok. I suggest to use Teensy LC as Teensy 3 is out of stock and I can't test it (though should be the same in this case)
