### ISSUE TITLE
Arduino UNO

### ISSUE THREAD

**Issue by BDebeuf** [dgatf/msrc#88]
Hi,

I'm using an Arduino UNO board for doing some tests with the project.
Communication is Smartport and Hobbywing 4.
I have the telemetry connection but all the values are zero.
I also see no RX led blinking.
With Sniffer I see the telegrams.
Where should I look to? It would be very nice to give me an idea.

**Comment by dgatf** [comment]
Which receiver protocol are you using? No blinking means that receiver is not being detected. Check that receiver protocol is correct and wiring
