### ISSUE TITLE
RP2040 Zero status LED is not used - different pin

### ISSUE THREAD

**Issue by NilsRo** [dgatf/msrc#94]
It seems that the status led does not work with RP2040 Zero as it is noted in the README. 

"Status led of the board blinks when sending telemetry. If it doesn't blink check connections and config"
Using the provided prebuild firmware with S.Port and Hobbwing V4 ESC.

Howtos: "As you might have noticed, GP25 of the Raspberry Pi Pico is routed to an onboard green LED. The RP2040-Zero did not have a similar LED on board (GP25 was thus freed) but its GP16 is hardwired to the DI (data input) of the integrated WS2812 LED."

**Comment by dgatf** [comment]
> Looking forward to a version with RGB indicator lights.

Fixed with 1a3f299f7e3c4cdfac2c9b15cf074ee6aff59de2

**Comment by dgatf** [comment]
> MSRC is more suitable for my application, using jtei's remote control. Currently, I have found that:
> 
>     GPS positioning is relatively slow, sometimes longitude and latitude only appear for a long time on JETI, and sometimes when the TX plug is unplugged and plugged in again, data such as longitude and latitude and date will appear;
> 
>     The voltage display data jumps, not at a fixed value;
> 
>     Unable to display the current value, I am not sure if it is the reason for the setting;

I've created a new issue for this. Please see #115
