### ISSUE TITLE
XBUS-Connection to AR8020T-Receiver

### ISSUE THREAD

**Issue by Antannah** [dgatf/msrc#95]
Hello all,

XBUS-connection doesn't seem to work. I tried with RP2040, Arduino Pro Mini 8MHz and Arduino Nano with manual Bus-delay by hand and Transistor as well.
No LED is flashing and I cannot determin in what state the microcontroller is.
Is this a bug with the receiver type or am I doing something wrong here?

Best regards
Norman

**Comment by dgatf** [comment]
Fixed with cf49a00969646c0d0d86ce73ce57088853f5b978
